### ISSUE TITLE
Update instructions for piggieback 0.3

### ISSUE THREAD

**Issue by bbatsov** [nrepl/weasel#72]
Piggieback now has a new home (https://github.com/clojure-emacs/piggieback and `cider/piggieback` on clojars), new maintainers and a new namespace (`cider.piggieback`). It'd be nice if the instructions here were reflected to update this, so newcomers won't be confused.

**Comment by mseddon** [comment]
When I tried to (only replacinh artifacts and namespaces) update to `cider.piggieback` I get an NPE trying to deref a future within cider.piggieback. Should this happen? My old setup works fine, but cider's project is not a drop in replacement for me at this stage, and I don't know which project is at fault.

**Comment by bbatsov** [comment]
> I get an NPE trying to deref a future within cider.piggieback.

What's the exact stacktrace?

> Should this happen? My old setup works fine, but cider's project is not a drop in replacement for me at this stage, and I don't know which project is at fault.

There's no CIDER's project - it's the same project as before. The artifact id is unfortunate. In hindsight I would have named it `nrepl/piggieback` and the namespace would have been `piggieback.core`.

**Comment by tomjakubowski** [comment]
Sorry for letting this go without a response for so long. I'm happy to accept a merge request, or if not I will try to make the requisite README changes myself sometime soon.

**Comment by bbatsov** [comment]
@tomjakubowski https://github.com/tomjakubowski/weasel/pull/73
